project:
  type: website

website:
  title: "MTRA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      # - Themen.qmd
      # - Mammakarzinom.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



