---
title: "Communication"
author: "Jorge Torres"
---

# Introduction

Effective communication in palliative care is crucial, particularly when discussing end-of-life care.

Research highlights that attitudes towards these sensitive conversations among both the public and healthcare professionals are positive and both view this topic as important.

A systematic review by Sharp et al. [@SharpEtAl2013] showed that the majority of older individuals (61%-91%) expressed a desire to discuss their end-of-life care, with many feeling comfortable or even enthusiastic about these conversations. Healthcare professionals generally also recognized the importance of these discussions, and most doctors (91%-97%) believed they are essential when dealing with severe chronic or terminal illnesses.

Despite these positive attitudes, actual end-of-life care discussions remain scarce.

Gamble et al. [@GambleEtAl1991] for example showed that while 81% of patients wanted to talk about end-of-life care with their physicians, only 11% had done so, and that these conversations were usually initiated by the patients themselves. Similarly, a 2021 Canadian poll revealed that although 59% of Canadians had discussed their care wishes with family, only 7% had communicated these preferences to a healthcare provider. [@TheAdvanceCarePlanninginCanadainitiative2021]

These findings underscore the need for more proactive and widespread communication about end-of-life care in palliative settings to ensure that patient preferences are understood and respected.

The significance of early integration into palliative care is well-established, with a considerable portion of the benefits attributed to effective communication. 
For example, Yoong et al. [@YoongEtAl2013] found that addressing symptoms and coping were the most prevalent components of palliative care clinic visits, which focused on building relationships and rapport with patients and their families and on understanding the illness, including prognostic awareness. 

However, healthcare professionals trained in communication should not use communication tools indiscriminately. 
This was demonstrated in a randomised study conducted by Curtis et al. [@CurtisEtAl2013] here a workshop designed to improve communication skills for oncology fellows, consisting of eight 4-hour sessions led by a physician and a nurse, was associated with the acquisition of new skills in delivering bad news and responding to emotions. However, there was no significant change in ratings of quality of care or quality of end-of-life care as assessed by patients, family, or clinicians.  
This suggests that improvements in communication skills observed in a controlled, standardized setting may not necessarily translate to enhancements in real-world clinical practice.

Moreover, an increase in patients’ depressive symptoms associated with the intervention was observed, indicating that awareness of prognosis may trigger negative experiences if not properly addressed by an expert.

Conversely, quality of care significantly improved among patients who rated their health status as “poor,” underscoring the importance of carefully selecting appropriate patients before delivering specialist palliative care.


Here a comparison with bereavement counselling might be helpful. Negative side effects of bereavement counselling are known to exist in psychotherapy and are the subject of current research. Since bereavement counselling is a psychosocial intervention and shares characteristics with psychotherapy (e.g., the establishment of a therapeutic alliance requiring trust and openness from the client), it is reasonable to assume that negative effects could also occur in bereavement counselling.

Negative effects can either be unintended detrimental consequences of properly applied interventions (side effects) or result from inappropriately applied interventions, such as unethical behavior and malpractice [@TelaarEtAl2023]. 

Examples of these negative effects can be found in a study by Moritz et al. [@MoritzEtAl2019] involving individuals with depression. While positive effects were reported by virtually all patients (95.6%), approximately half of them (52.6%) also reported experiencing at least one adverse event.

These considerations highlight the necessity for a judicious approach to the use of communication in palliative care, ensuring that it is targeted to those who will benefit most, and avoiding potential adverse effects for others.



Technical skills are less important than coming across as approachable, honest, warm and confident.

The Cardiff six-point toolkit[@KissaneEtAl2017]: 
## Comfort
## Language
## Question style
## Listening / use of silence
## Reflection
## Summarising


Losing a loved one to death is an inherent part of human life. About 7% of bereaved older adults, however, will develop the mental health condition of Complicated Grief (CG). [@ShearEtAl2013]

Negative side effects of bereavement counselling are known to exist in psychotherapy and are the subject of current research

Since bereavement counselling is a psychosocial intervention and therefore shares some characteristics with psychotherapy (e.g., the establishment of a therapeutic alliance requiring trust and openness from the client), it is reasonable to assume that negative effects could occur also in bereavement counselling.

Negative effects can either be unintended detrimental consequences of properly applied interventions (side effects) or result from inappropriate applied interventions, e.g., unethical behavior and malpractice.[@TelaarEtAl2023]

For example in a Study of depression in a population of individuals with depression the positive and negative effects of psychotherapy effects were quantified. Positive effects were reported by virtually all patients (95.6%). 
At the same time, approximately half of them reported at least one adverse event (52.6%). Among these, side effects (38.5%) and malpractice (26.7%) were significantly more prevalent than unethical conduct (8.1%). [@MoritzEtAl2019]

That is why it is of outmost importance to choose patients fit for beraavement counselling whisley. 
For example, at least some individuals experiencing prolonged depression during bereavement may have been depressed prior to the loss and thus may be more accurately viewed as suffering from chronic depression rather than chronic grief.[@BonannoEtAl2004]

However complicated grief constitutes a distinct psychopathological diagnostic entity distinct from eg posttraumatic stress disorder, major depressive disorder and adjustment disorder. Complicated grief is characterized by a unique pattern of symptoms following bereavement that are typically slow to resolve and can persist for years if left untreated.  

Using prospective longitudinal data on an older sample beginning prior to the death of a spouse, Bonanno et al. [@BonannoEtAl2002] distinguished 5 unique trajectories of bereavement outcome: 

- common grief 
- chronic grief 
- chronic depression 
- depression followed by improvement
- resilience.

Currier et.al.[@CurrierEtAl2008]  separated Interventions for bereaved persons  in

- Universal 
- Selective
- Indicated

Universal interventions target anyone who suffers bereavement and do not distinguish on the basis of death-related risk factors or pre-intervention functioning.

Although selective interventions do not focus on highly distressed grievers per se, they are geared toward particular groups of bereaved individuals who face a heightened risk of experiencing distress symptoms, such as those who lose a child to a violent death.

Lastly, there is a third group of indicated interventions (e.g., Wagner, Knaevelsrud, & Maercker, 2006) that restrict selection to those manifesting problems adapting to loss, which can include symptoms of an established psychiatric disorder (e.g., major depression; Reynolds et al., 1999) or other clinically significant difficulties (e.g., loss-related intrusions, anxiety, and guilt feeling) 

In this study Interventions targeting universal populations and higher risk grievers failed to produce good outcomes. Conversely, when there were specific difficulties adapting to loss, effect sizes compared favorably with the successes shown for psychotherapy in general were observed.


# Discussing Serious News

Learn best practices for having patient-centered conversations about a serious illness diagnosis.

# Discussing Prognosis With Patients and Caregivers

Learn how to effectively discuss prognosis with patients and their caregivers.

# Clarifying Patient Goals of Care

Learn best practices for building trust, eliciting patient values, and having patient-centered conversations about goals of care.

# Leading a Patient and Caregiver Meeting

Learn to effectively lead meetings that help patients and caregivers become aligned around the patient’s goals.


# Care Planning

Learn techniques to help patients and their caregivers plan for the future, both during the early stages of a serious illness and as a disease progresses.
