---
title: "Gutartige Erkrankungen"
author: "Jorge Torres"
format: 
  html: 
    fig-width: 8
    fig.asp: 0.618
slide-format: revealjs
bibliography: mta-schule.bib
csl: american-medical-association.csl
execute:
  warning: false
---

# Einführung 

## Radioonkologie

Die Radioonkologie wird weltweit durch Organisationen wie die ESTRO (Europa) und die ASTRO (USA) sowie andere nationale Gesellschaften vertreten. Die ESTRO konzentriert sich hauptsächlich auf die Strahlentherapie bei Krebs. In ihrem jüngsten Strategiepapier wird betont: „Es wird zwar anerkannt, dass sich die nicht-onkologischen Indikationen für die Strahlentherapie im Laufe der Zeit erweitern können, doch die formale Aufnahme des Begriffs ‚Onkologie‘ in das Visionspapier unterstreicht, dass die Hauptindikationen für die Strahlentherapie und damit der Schwerpunkt dieser Disziplin weiterhin in der Onkologie liegen." Die ASTRO konzentriert sich ebenfalls auf die Strahlentherapie bei Krebspatienten und erwähnt nicht ausdrücklich die Bestrahlung bei Nicht-Krebserkrankungen. [@IORBC]

Die Nutzung der Strahlentherapie variiert stark je nach Erkrankung und Land. Zum Beispiel wird die Strahlentherapie im Vereinigten Königreich, in großen Teilen Europas und Nordamerikas nur selten für diese Indikationen verwendet [@McKeownEtAl2015].

Trotzdem wird die Strahlentherapie schon lange für nicht-krebsartige Erkrankungen genutzt. Die erste gutartige Erkrankung, die mit Strahlentherapie behandelt wurde, war eine juvenile Arthritis im Jahr 1898. [@TorresRoyoEtAl2020]

In Deutschland spielt die Strahlentherapie bei gutartigen Erkrankungen eine wichtige Rolle. Im Jahr 2016 wurden hier **258.946** gutartige entzündliche Erkrankungen und Tumoren (1%) mit Strahlentherapie behandelt.
@fig-plot-PropGutartig zeigt, dass die Strahlentherapie sogar häufiger bei gutartigen als bei bösartigen Erkrankungen eingesetzt wurde [@PoppEtAl2020].

Von den über 300 aktiven strahlentherapeutischen Einrichtungen in Deutschland bietet jede einzelne Strahlentherapie bei gutartigen Erkrankungen an.

Die Behandlung nicht-bösartiger Erkrankungen mit ionisierenden Strahlen in niedrigen bis mittleren, teilweise auch hohen Dosen ist oft erfolgreich. Diese Erfolge tragen häufig zur Erhaltung oder Wiederherstellung der Lebensqualität bei, zum Beispiel durch Schmerzlinderung oder Verbesserung zuvor eingeschränkter Funktionen. [@MueckeEtAl2022]


```{r plt_PropGutartig}
#| label: fig-plot-PropGutartig
#| echo: false
#| out-width: 70% 
#| fig-cap: "Anteil benigne Erkrankungen"


library(ggplot2)
library(dplyr)
library(tidyr)
library(scales)
library(ggtext)

ProzBenigne <- 0.55

# Wrangle data to get a data frame in the format we need it in to make our donut chart
ProportionBenigne <- tibble(x = 1, y = ProzBenigne) %>% 
  mutate(y_negative = 1 - y) %>% 
  pivot_longer(cols = -x) 


highlight_color <- "#9dccda"


font_family <- "Ubuntu"

# Create a nicely formatted big number to go in the donut hole
big_number_text_label <- percent(ProzBenigne, accuracy = 1)


# Create our plot
ggplot(data = ProportionBenigne,
       aes(x = x,
           y = value,
           fill = name)) +
  
  # Add a bar, but don't add the legend
  geom_col(show.legend = FALSE) +
  
  # A pie/donut chart is a bar chart with polar coordinates
  # Add polar coordinates and set the direction to -1 
  # so the filled in part starts at the top and goes clockwise
  coord_polar(theta = "y",
              direction = -1) +
  
  
  # Set the limits, which is important for adding the hole
  xlim(c(-2, 2)) +
  
  # Set a color scale with the highlighted section in whatever color
  # is chosen with the highlight_color argument and the rest in a light gray
  scale_fill_manual(values = c(highlight_color ,  "grey90")) +
  
  # Set theme_void() to remove grid lines and everything else from the plot
  theme_void() +
  
  # Add the big number in the center of the hole
  annotate(geom = "text",
           label = big_number_text_label,
           family = font_family,
           fontface = "bold",
           color = highlight_color,
           size = 16,
           x = -2,
           y = 0)+ 

labs(
        title = "<p>Die Behnalung <span style='color:#9dccda'>benigne Erkrankungen</span> spielt eine<br><span style='color:#9dccda'> Wesentliche Rolle</span> in Deutschland</p>",
        subtitle = "",
        caption = "Anzahl der Strahlentherapien untergliedert nach Diagnosegruppen.<br>Die Daten beziehen sich auf EBM, GOÄ und OPS sowie konsolidiert auf das Jahr 2016."
  )+
theme(
      plot.title =  element_markdown(
          
                                    hjust=0.5,
                                    family = "Ubuntu",
                                    size = 20,
                                    color = "#808080",
                                    face = "bold",
                                    ),
      #plot.title.position = "plot",
     plot.caption = element_markdown(
                                      family = "Ubuntu",
                                      hjust=0.5,
                                      #vjust=3,
                                      size = 10,
                                      color = "#808080"
                                    ),
      )


```


# Strahlentherapie

# Schmerzlindernde Wirkung 

# Antientzündliche Wirkung 

In der Regel erfolgen 6 Bestrahlungen mit sehr niedrigen Einzeldosen von 0,5 Gy mit einer Gesamtdosis von 3,0 Gy inerhalb von 3 Wochen. Im Falle eines Teilerfolgs ist eine 2. Serie möglich.

# Erkrankungen: 

## Fersensporn

### Ätiologie 

### Anatomie

### Histology

### Korrelation

#### Alter

#### Geschlecht

#### Gewicht

#### Fußstellung 

#### Plantar fasciitis

## Schmerzsyndrom der Achillessehne
## Entzündung des Schultergelenks
## Epicondylitis radialis/ulnaris
## Arthrose 
## Morbus Dupuytren
## Morbus Ledderhose
## Endokrine Orbitopatie
## Meningiome

# Literaturverzeichnis 

