---
title: "Kopf-Hals Plattenepithelkarzinome"
format: 
  html: 
    fig-width: 8
    fig.asp: 0.618
slide-format: revealjs
bibliography: mta-schule.bib
csl: american-medical-association.csl
execute:
  warning: false
crossref: 
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  sec-prefix: Abschnitt
  fig-title: Abbildung
  tbl-title: Tabelle
---

Kopf-Hals-Tumoren 

# Sprechstunde

## Im Kurze

Hier wird ausschließlich Bezug auf die Plattenepithelkarzinome genommen, die in der Mundhöhle, Lippe, Oro-, Hypopharynx und Larynx entstehen, während Nasopharynx-, Nasenhaupt-/Nasennebenhöhlen- und Speicheldrüsenkarzinome nicht adressiert werden. 75% der Tumore besteht eine Assoziation zu Nikotin- und Alkoholkonsum. 

HPV-assoziierten Tumore im Oropharynx, die häufiger bei jüngeren PatientInnen auftreten, seltener eine Assoziation zu Nikotin und Alkohol aufweisen und eine deutlich bessere Prognose als HPV-negative Tumore aufweisen. @zotero-4833

--- 

Around 75%-85% of SCCHN is due to tobacco use and alcohol consumption, although human papillomavirus (HPV) infection as a cause of oropharyngeal cancer is increasing.

HPV-positive patients with oropharyngeal cancer have a significantly better outcome than patients diagnosed with HPV-negative disease. HPV-positive SCCHN outside of the oropharynx is rare (<6%). 

Every patient should undergo evaluation of their nutritional status, comorbidities, cardiopulmonary and renal function, frailty index (for geriatric patients), psychological and social status and dental status with rehabilitation in case of foreseen RT. In case of significant malnutrition, defined as weight loss of more than 10% during the 6 months before diagnosis, nutritional improvement via enteral route through a feeding tube is highly recommended before starting treatment. 

@MachielsEtAl2020


## Onkologische Anamnese 
ICD10 Codes im App 

## Befunde müssen bei dieser Entität zwingend genannt sein? (Histologie, spezielle Untersuchung?) 

CROSSLINK: Onkologische Anamnese allgemein 

1.2 Rechtfertigende Indikation 
- Begründung der Strahlentherapie nach Leitlinienlage mit entsprechenden Literaturangaben zB als Tabelle, idealerweise mit Verlinkungen zu den jeweiligen Papers 

- Ein- und Ausschlusskriterien 

1.3 Bestrahlungsverordnung 
- Zielvolumenbeschreibung ggf. mit Abkürzungsverzeichnis für Benennung 
- Bestrahlungsdosis und Fraktionierung (mit Abkürzung der Verordnungsvorlage im Aria, falls vorhanden) 

- Typische Einträge bzgl KM, Maske, BB, Gewicht, CHT, sonstiges bei dieser Entität 

CROSSLINK: Kontrastmittel 

1.4 Bestrahlungsvorbereitung 
- Aufklärung (Name der Aufklärung in den Termin eintragen) und Einwilligung (häufigste Nebenwirkungen ggf. mit Eintrittswahrscheinlichkeit) 

- ggf. vorgeschaltete Untersuchungen (zB PL-MRT oder LuFu) 
- Planungs-CT (ggf. mit Besonderheiten von Einträgen in den Termin oder Dauer) und benötigte Lagerung(-shilfen) 

-  ggf. Zahnsanierung, Spacer etc. inkl. Beschreibung der internen to dos (Beispiel bei Zahnsanierung: Briefvorlage an Zahnarzt o.ä.) 

- Hinweise zu Besonderheiten (Abstand zu OP etc.) 

CROSSLINK: Prozessbeschreibung Aufklärung und Dokumentation, Tumorboardanmeldung 

1.5 Konkomittante Systemtherapie 
- Chemotherapie / Immuntherapie / Hormontherapie während Bestrahlung (ggf. mit “Chemotherapie”-Encounter, Stationsjournal etc) 
- Organisation und Koordination (wo Termine machen, CHT-Reiter im Aria, etc) 

- Wird RT ggf. bei bestimmten Medikamenten unterbrochen?  

2. Planung – Wird separat angelegt und später verlinkt. Dieser Punkt muss nicht i.R. der Entität ausgefüllt werden  
- CT-/MRT-Planung: Durchführung und Vorgaben 
- Zielvolumendefinition: GTV, CTV, PTV 
- Organe at Risk (OAR) 
- Planabnahme und Dosisverteilung 

- Bestrahlungstechnik (IMRT) 

3. Gerät  
-  Besonderheiten Arztgespräch für diese Entität 

- CROSSLINK: Ersteinstellung, Protokollvisite, Wochenkontrolle, Abschlussgespräch, Planfreigabe, Arztgespräch allgemein, supportive Therapie, Dokumentation Nebenwirkungen CTCAE 

4. Nachsorge 
- Zeitpunkt und Art der Nachsorgeuntersuchungen bei dieser Entität 
- Dokumentation von Nebenwirkungen (akut/spät) im Nachsorgekalender 

CROSSLINK: Nachsorge allgemein 

5. Wichtige Studien 
- Aktuelle Studienlage zur Entität (wenn möglich mit Verlinkung zum Paper und ggf 1 Satz zur Aussage) 
- ggf Hinweise auf Register oder laufende Studien 
- ggf Möglichkeiten zur Studieneinschlussprüfung 