---
title: "Intro"
# page-layout: custom
section-divs: false
toc: false
---

::: {.hero-banner}

::: {.hero-text}

# Einführung


Hier findest du Lernziele und Inhalte, die auch in der Prüfung wichtig sind.

Die Themen geben eine allgemeine Einführung in die verschiedenen medizinischen Bereiche.


Viel Erfolg beim Lernen!


:::

:::

::: {.content-block}
::: {.features}

::: {.feature}
### Mammakarzinom
Du wirst das Krankheitsbild des Mammakarzinoms in seiner typischen Form, einschließlich der Entstehung, Diagnose und Behandlung, verständlich erklären können.

::: {.learn-more}
[Mehr erfahren »](Mammakarzinom.qmd)
:::

:::

::: {.feature}
### Gutartiger Erkrankungen 
Du wirst verstehen, wie niedrig dosierte Strahlentherapie Schmerzen lindert. Du wirst lernen, wie die entzündungshemmende Wirkung funktioniert. Du wirst die verschiedenen Krankheitsbilder von Gelenk- und Weichteilerkrankungen kennenlernen.

::: {.learn-more}
[Mehr erfahren »](Gutartig.qmd)
:::

:::

::: {.feature}
### Enfermedades Benignas 
Comprenderás cómo la radioterapia de baja dosis alivia el dolor. Aprenderás cómo funciona el efecto antiinflamatorio. Conocerás los diferentes cuadros clínicos de las enfermedades articulares y de los tejidos blandos. Podras explicar el tratamiento de estas enfermedades en cuanto a la dosis y el número de fracciones. 

::: {.learn-more}
[Más información »](Benignas.qmd)
:::

:::


:::
:::
