---
title: "Prostatakarzinom"
author: "Jorge Torres"
format: 
  html: 
    fig-width: 8
    fig.asp: 0.618
slide-format: revealjs
bibliography: mta-schule.bib
csl: american-medical-association.csl
execute:
  warning: false
crossref: 
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  sec-prefix: Abschnitt
  fig-title: Abbildung
  tbl-title: Tabelle
---

# Tumorausdehnung 

Die Stadien T1-2 N0 M0 werden unter der Bezeichnung lokal begrenztes Prostatakarzinom zusammengefasst. 
Das lokal fortgeschrittene Prostatakarzinom umfasst die Stadien T3-4 N0 M0. 
Die Stadien N1und/oder M1 werden als fortgeschrittenes bzw. metastasiertes Prostatakarzinom bezeichnet. @DeutscheKrebsgesellschaftEtAl2024


| Stadium                     | Beschreibung                            |
|-----------------------------|-----------------------------------------|
| T1-2 N0 M0                  | Lokal begrenzt                          |
| T3-4 N0 M0                  | Lokal fortgeschritten                   |
| N1 und/oder M1              | Fortgeschrittenes bzw. metastasiertes Prostatakarzinom |

: Stadien des Prostatakarzinoms: Hier werden die Stadien und deren Klassifikation zusammengefasst. {#tbl-Klassifikation .striped .hover}


# Wahrscheinlichkeit von Knochenmetastasen 

| PSA-Wert (ng/ml)       | Wahrscheinlichkeit (%) | Bereich (%)   |
|------------------------|------------------------|---------------|
| <10                    | 2,3                    | 1,7 - 3,0     |
| 10-19,9                | 6                      | 4,6 - 7,6     |
| 20-49,9                | 15,9                   | 12,9 - 19,2   |
| 50-99,9                | 39,2                   | 29,0 - 41,8   |
| >100                   | 74,9                   | 70,8 - 78,7   |

: Prävalenz von Knochenmetastasen in Abhängigkeit vom PSA-Wert bei Prostatakrebs. {#tbl-KnochenmetastasenRisiko .striped .hover}


das Vorliegen von Knochenmetastasen bei ca. 6 % der Patienten mit einem PSA-Wert von 10-20 ng/ml zu hoch sei, um diese Unsicherheit vor dem Hintergrund einer Entscheidung zu einer Operation zu tolerieren. 
Aus diesem Grund wurde nach erneuter Abstimmung der Grenzwert 10 ng/ml belassen. @DeutscheKrebsgesellschaftEtAl2024


## Wann Staging? 

Bei Vorliegen ***einer*** folgenden Risikofaktoren soll ein Staging erfolgen. @DeutscheKrebsgesellschaftEtAl2024

| Risikofaktor                                  | Prävalenz von Knochenmetastasen | 
|-----------------------------------------------|---------------------------------|
| PSA-Wert >10 ng/ml                            | 6 %                             | 
| Lokal fortgeschrittener Tumor (T3/4)          | 47 %                            | 
| Gleason-Score >7                              | 28 %                            | 
| Knochenschmerzen oder Anstieg der alkalischen Phosphatase | Nicht spezifiziert  | 

: Risikofaktoren für das Staging bei Prostatakarzinom {#tbl-Risikofaktoren .striped .hover}

## Häufigkeit nach Zonen

| Prostatazone                   | Anteil an Prostatakarzinomen | Beschreibung                                                  |
|--------------------------------|------------------------------|----------------------------------------------------------------|
| Zentrale Zone                  | 10 %                         |                 |
| Transitionalzone               | 15–20 %                      |  inzidentelle Karzinome                                  |
| Periphere oder posterolaterale Zone | 70–75 %                |  manifeste Karzinome                              |
: Anatomische Zonen der Prostata und ihre Häufigkeit von Prostatakarzinomen gemäß dem McNeal-Modell @DeutscheKrebsgesellschaftEtAl2024 {#tbl-Zonen .striped .hover}

# Überwachung

Von Überdiagnose spricht man, wenn Karzinome entdeckt werden, die den Patienten in seiner Lebenserwartung nicht bedrohen. Sie zu behandeln bedeutet eine Übertherapie. @DeutscheKrebsgesellschaftEtAl2024


Männer mit neu diagnostiziertem PCa und mehreren Komorbiditäten (Charlson Comorbidity Index (CCI)-Wert >2) zeigten unabhängig von ihrem Alter zum Zeitpunkt der Diagnose nach 10 Jahren Nachbeobachtung eine sehr geringe PCa-abhängige Mortalität, so dass hier ein Watchful Waiting diskutiert werden muss. @DeutscheKrebsgesellschaftEtAl2024

Die Tumoraggressivität hatte kaum Einfluss auf das Gesamtüberleben. 
Hingegen hatten Männer mit einem CCI-Wert <1 ein geringes Risiko, innerhalb von 10 Jahren zu versterben, so dass in dieser Gruppe eine strukturierte Überwachung im niedrigen Risiko bzw. eine aktive Therapie bei höherer Aggressivität erfolgt. @DeutscheKrebsgesellschaftEtAl2024

Eine Aktive Überwachung bei ansonsten gesunden und für eine kurativ intendierte Therapie geeignete Patienten hat das Ziel, eine rechtzeitige aktive Behandlung bis zu einem Zeitpunkt aufzuschieben, an dem sich Hinweise für eine Progression ergeben oder der Patient diese wünscht. @DeutscheKrebsgesellschaftEtAl2024

Die wesentliche Rolle der regelmäßigen PSA-Wertmessung beruht auf der damit verbundenen validen Option, die PSA-Verdopplungszeiten (PSADT) adäquat berechnen und die PSA-Dichte (PSAD) bei ebenfalls durchgeführter mpMRT der Prostata objektiv bestimmen zu können. @DeutscheKrebsgesellschaftEtAl2024


| ISUP-Gruppe | Kontrollintervall       | 
|-------------|-------------------------|
| Gruppe 1    | Alle 6 Monate           |
| Gruppe 2    | Alle 3 Monate           | 

: Kontrollintervalle bei Aktiver Überwachung {#tbl-Kontrollintervall .striped .hover}


| Patientengruppe             | Zeitpunkt der Re-Biopsie      | 
|-----------------------------|-------------------------------|
| Mit initialer mpMRT         | Nach 12–18 Monaten            | 
| Ohne initiale mpMRT         | Innerhalb von 6 Monaten       |

: Zeitpunkt der ersten Re-Biopsie bei Patienten unter Aktiver Überwachung {#tbl-Rebiopsie .striped .hover}

Bei signifikantem PSA-Anstieg (Verdopplungszeit <3 Jahre) sollte eine erneute mpMRT mit gezielter und systematischer Re-Biopsie erfolgen. 
Eine alleinige Progression des PSA-Wertes und/oder einer mpMRT-Läsion sollte nicht zum Abbruch der Aktiven Überwachung führen. @DeutscheKrebsgesellschaftEtAl2024

Die Aktive Überwachung soll beendet werden, bei: 

- Upgrading zu ISUP Gruppe 2 mit ungünstigem Risikoprofil*  
- Upgrading zu >= ISUP Gruppe 3
- Lokal fortgeschrittenem Tumorstadium (≥cT3 und/oder cN+) 

*cribriformes oder intraduktales Wachstum, Anteil Gleason-Muster 4 über 10 %.

# Therapie 

Patienten mit Prostatakarzinom aller Risikogruppen sollen bei Verwendung einer Standardfraktionierung mit einer Dosis von mindestens 74,0 Gy bis ca. 80 Gy bestrahlt werden. @DeutscheKrebsgesellschaftEtAl2024

Der Stellenwert der moderat hypofraktionierten Strahlentherapie ist trotz zahlreicher abgeschlossener Phase-III-Studien nicht abschließend geklärt, da insgesamt keine ausreichend langen Nachbeobachtungszeiten vorliegen. @DeutscheKrebsgesellschaftEtAl2024



| Risikogruppe       | PSA-Wert             | Gleason-Score        | cT-Kategorie    |
|--------------------|----------------------|----------------------|-----------------|
| Niedriges Risiko   | <10 ng/ml           | 6                    | ≤ 2a            |
| Intermediäres Risiko | 10–20 ng/ml        | 7                    | 2b              |
| Hohes Risiko       | >20 ng/ml           | ≥8                   | ≥ 2c            |

: Risikogruppen für lokal begrenztes Prostatakarzinom {#tbl-Risikogruppen .striped .hover}


Die Low-Dose-Rate-Brachytherapie (LDR-Brachytherapie oder Seedstherapie) ist für Patienten mit Prostatakarzinom des niedrigen Risikoprofils ein alternatives kuratives Therapieverfahren zur radikalen Prostatektomie und zur perkutanen Strahlentherapie. 
Dabei hat sich die transperineale Implantation von Jod-125 bzw. Palladium-103-Seeds zu einem Standard entwickelt. @DeutscheKrebsgesellschaftEtAl2024

Patienten mit einem Prostatakarzinom hohen Risikos sollen keine LDR-Monotherapie erhalten. @DeutscheKrebsgesellschaftEtAl2024

Die HDR-Brachytherapie, kombiniert mit der perkutanen Strahlentherapie, ist eine primäre Therapieoption bei Patienten mit Tumoren des mittleren und hohen Risikoprofils. @DeutscheKrebsgesellschaftEtAl2024

Patienten mit einem unilateralen, lokal begrenzten Prostatakarzinom niedrigen Risikos kann eine fokale Therapie angeboten werden, wenn diese sowohl Standardtherapien als auch eine Active Surveillance (AS) ablehnen. @DeutscheKrebsgesellschaftEtAl2024

Patienten mit einem Prostatakarzinom des hohen Risikoprofils, die eine radikale Prostatektomie wünschen, sollen über das erhöhte Risiko für positive Resektionsränder und für ein Krankheitsrezidiv sowie die daraus häufig resultierenden zusätzlich notwendigen Maßnahmen (z. B. hormonablative Therapie, Strahlentherapie) aufgeklärt werden. @DeutscheKrebsgesellschaftEtAl2024



