---
title: "Rektum"
format: 
  html: 
    fig-width: 8
    fig.asp: 0.618
slide-format: revealjs
bibliography: mta-schule.bib
csl: american-medical-association.csl
execute:
  warning: false
crossref: 
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  sec-prefix: Abschnitt
  fig-title: Abbildung
  tbl-title: Tabelle
---

# Rektalkarzinom ICD10: C20

Rektumkarzinome sind Tumoren, deren aboraler Rand bei der Messung mit dem starren Rektoskop **16 cm oder weniger** von der **Anokutanlinie** entfernt sind (USA >12cm ab ano = Kolonkarzinome). @DeutscheKrebsgesellschaftEtAl2019

## Behandlung: Grundprinzipien und Entwicklung

Ohne Behandlung (oder rein palliative Behandlung) leben Patienten im Durchschnitt 9,8 Monate nach Diagnose. @PestanaEtAl1964
Im 1982 Heald führte der totalen mesorektalen Exzision (TME). Bei der TME wird das komplete Mesorektum entfernt, wodurch die Lokalrezidivrate auf ~3-7 % gesenkt werden konnte. Die OS nach 5 Jahren war 87 %. @HealdRyall1986
Die TME setzte sich in den folgenden zwei Jahrzehnten international durch und setzte einen neuen chirurgischen Standard. @DeschnerEtAl2021

1985 zeigte die Gastrointestinal Tumor Study Group @GastrointestinalTumorStudyGroup1985 , dass die adjuvante Therapie Vorteile bei der lokalen Kontrolle (Rezidivrate/Disease-Free Survival) hatte, insbesondere die **Radiochemotherapie.**

Die Radiochemotherapy wurde dann als **neoadjuvantes** Konzept untersucht, um die Ergebnisse weiter zu verbessern.

Die theoretischen Vorteile waren @DeschnerEtAl2021 :

- Frühere Behandlung von Mikrometastasen 
- Besseres Ansprechen des Tumors: eine intakte Blutversorgung macht die Bestrahlung/Chemotherapy effektiver.
- Geringeres Risiko einer Tumorausbreitung während der Operation 
- Geringere Toxizität - ein gesünderer Darm verträgt die Behandlung besser.
- Durch das downstaging erhöhte die Chancen auf Sphinkter-sparenden Operationen.

1997 zeigte der "Swedish Rectal Cancer Trial" @SwedishRectalCancerTrial1997, dass die neoadjuvante RT sowohl die lokale Kontrolle als auch das Gesamtüberleben verbesserte, dies war ein Wendepunkt. 

Trotz besserer lokaler Kontrolle blieb die Fernmetastasierung ein großes Problem. Die **adjuvante Chemotherapie** sollte dem entgegenwirken, doch die geringe Compliance begrenzte ihren Nutzen. @IVEtAl2022

Die deutsche CAO/ARO/AIO-94 Studie @SauerEtAl2004 bestätigte, dass die neoadjuvante CRT der adjuvanten CRT in lokal fortgeschrittenen Fällen überlegen war.

Die Stockholm-III-Studie @ErlandssonEtAl2017 zeigte, dass eine Kurzzeit-Therapie mit verzögerter Operation ebenso wirksam war wie eine Kurzzeit-Strahlentherapie mit sofortiger Operation- was die Möglichkeit einer zusätzlichen Chemotherapie vor der Operation eröffnete.

Daraus entwickelte sich das Konzept der totalen neoadjuvanten Therapie (TNT) [@BahadoerEtAl2021; @ConroyEtAl2021], bei der alle Behandlungen **(Radiochemotherapy und Chemotherapy)** vor der Operation durchgeführt werden. 

TNT verbessert die Ansprechraten, und bei einigen Patienten, die ein klinisch komplettes Ansprechen (cCR) erreichen, kann sogar eine Operation vermieden werden dies zegite z.B. die OPRA-Trial @Garcia-AguilarEtAl2022, wodurch sich das Interesse an einer nichtoperativen Behandlung in ausgewählten Fällen verschiebt. 


Sonderfall: Neulich Patienten mit bestimmten genetisch bedingten Tumorarten (MSI-H/dMMR) erhalten jetzt stattdessen zuerst eine Immuntherapie die zur eine kommplete Remision führt. @CercekEtAl2022

# Spreechstunde 

## Dokumentation des Leistungsstatus 

Die Dokumentation des Leistungsstatus erfolgt nach der Einteilung der Eastern Cooperative Oncology Group (ECOG) 

## Obligatorische Untersuchungen

- Starre Rektoskopie (Goldstandard zur Definition des Tumorabstands ab ano)
- Qualitätsgesicherte MRT Becken
- CT Thorax/Abdomen ggf. 
  - Sonographie Abdomen (Empfehlung S3 Leitlinie)
- CEA
- Histologie/ MSI (Mikrosatelliteninstabilität)
- DPD Test

##### DPD Test

Bei Vorliegen eines DPD-Mangels kann das Medikament 5-FU bzw. Capecitabin (Prodrug) nicht verstoffwechselt werden und es kommt zu schweren Toxizitäten. 
30 % dieser gefährlichen Reaktionen sind durch einen DPD-Mangel erklärbar. Dementsprechend ***muss*** beim Erstgespräch der DPD-Test vorliegen, bzw. wird abgenommen. 

Hierbei handelt sich um eine genetische Untersuchung im Sinne des Gendiagnostik-/Gentechnikgesetzes, d. h., es sind bestimmte Vorgaben einzuhalten (Aufklärung, Einwilligung, Durchführung durch einen Arzt und Mitteilung der Ergebnisse). 

DPYD-Varianten sind als pharmakogenetische Eigenschaften mit hoher Bedeutung einzuordnen.

Wird eine klinisch relevante DPD-Variante gefunden, ist dem Patienten gemäß §10 Abs.1 Satz2 GenDG eine genetische Beratung anzubieten. 
Der Patient kann auf eine genetische Beratung nach dem Vorliegen der Testergebnisse verzichten,
der Verzicht ist schriftlich zu dokumentieren.
Wenn eine genetische Beratung nach dem Vorliegen des Testergebnisses gewünscht wird, darf die Beratung nur durch einen Facharzt für Humangenetik oder einen nach dem GenDG qualifizierten Arzt vorgenommen werden. [@DGHO2020; @2020]

##### Starre Rektoskopie

Beim Rektumkarzinom sollte die starre Rektoskopie mit Höhenangabe des Tumorunterrandes obligater Bestandteil der präoperativen Diagnostik sein. @DeutscheKrebsgesellschaftEtAl2019 

##### MRT

Die Befundbeschreibung soll eine Aussage über den Abstand zur mesorektalen Faszie beinhalten. @DeutscheKrebsgesellschaftEtAl2019 

##### Endosonographie 

Im Falle eines mutmaßlichen T1-Karzinoms eine Endosonographie, hier ist die CT nicht geeignet. 
Bei der Differenzierung von T2 und T3-Karzinomen wies die Endosonographie wiederum eine höhere Sensitivität im Vergleich zu MRT und CT auf bei vergleichbarer Spezifität. In der Endosonographie lässt sich die mesorektale Faszie nicht darstellen. @DeutscheKrebsgesellschaftEtAl2019 


##### Laut S3 Leitlinie beinhaltet das Staging folgende Untersuchungen @DeutscheKrebsgesellschaftEtAl2019 : 

- Starre Rektoskopie
- Komplette Koloskopie  
- CEA-Wert (sollte präoperativ bestimmt werden)
- Abdomensonographie (primär zur Klärung von Lebermetastasen)
- Rö-Thorax (2 Ebenen)
  - Im Falle eines unklaren Befundes oder des Verdachtes auf Fernmetastasen oder Infiltration von Nachbarorganen oder umgebende Strukturen soll ein Mehrzeilen-CT des Abdomens und Beckens erfolgen bzw: 
  - Bei Verdacht auf Lungenmetastasen ein CT des Thorax
- MR (CT)-Becken mit Angabe Abstand des Tumors zur mesorektalen Faszie 
- Rektale Endosonographie bei lokal begrenztem Tumor


##### PET-CT 

bei lokal fortgeschrittener Erkrankung

### Anforderungen an die Histopathologie

#### Adenokarzinom-Subtyp-Klassifikation
#### Grad der Tumordifferenzierung
#### MMR/MSI-Status

Bei etwa 3-5% der Patienten mit lokal begrenztem Rektumkarzinom ist ein DNS-
Mismatch-Reparaturdefekt (dMMR) bzw. eine Mikrosatelliten-Instabilität (MSI-H) in der Tumorbiopsie
nachweisbar. 

Dostarlimab kann eine klinische komplette Remission erreichen. So dass eine Radiochemotherapie und eine Operation unterbleiben kann. Eine [Handreichung der DGHO](https://www.dgho.de/publikationen/stellungnahmen/gute-aerztliche-praxis/immuncheckpoint-inhibitoren/immuncheckpointinhibitor-20230508.pdf) kann bei der Beantragung dieser Therapie hilfreich sein. 

#### KRAS/NRAS/BRAF-Mutationsstatus

### Entfernung vom Analrand

Die präoperative Messung der Höhenangabe des Tumors mit dem flexiblen Endoskop ist unzuverlässig. 
Zuverlässiger sind die **Höhenangaben mit dem starren Rektoskop.** @DeutscheKrebsgesellschaftEtAl2019
Dementsprechend werden letztere dokumetiert. Ab Anokutanlinie:  

- oberes Rektumdrittels (12 - 16 cm)
- mittleres Rektumdrittels (6 - <12 cm)
- unteres Rektumdrittels (< 6 cm) unterteilt



### Rechtfertigende Indikation 

In Folge werden Kandidaten für neoadjuvante Therapie erleutert. 

#### Stadium I (cT1-2N0)

##### Neoadjuvante vs. Upfront-Chirurgie

Bei T1-High-Risk-Karzinomen (G3/4 u./o. Lymphgefäßinvasion) und bei T2 Karzinomen liegt das Auftreten von Lymphknotenmetastasen bei 10–20%, sodass die alleinige lokale Exzision nicht empfohlen werden kann und eine primäre radikale Operation oder eine sekundäre radikale Nachoperation indiziert sind. 

Lehnt der Patient in dieser Situation eine radikale Nachoperation ab, so kann eine **adjuvante Radiochemotherapie** erwogen werden.

Dahingengend haben Rektumkarzinome im UICC-Stadium I (T1/2, N0)  nach alleiniger radikaler Operation mit adäquater totaler mesorektaler Exzision (TME) für Tumoren im unteren/mittleren Drittel sowie partieller mesorektaler Exzision (PME) für Tumoren im oberen Rektumdrittel niedrige Lokalrezidiv- und Fernmetastasenraten (3 % Lokalrezidive bzw. weniger als 10 % Fernmetastasen nach 10 Jahren. 

Dementsprechend soll bei Tumore in UICC-Stadium I (cT1-2, N0) eine präoperative Therapie nicht durchgeführt werden. @DeutscheKrebsgesellschaftEtAl2019 

##### Tiefsitzenden T1, N0 high-risk Tumore

Für Patienten mit tiefsitzenden T1, N0 high-risk (G3/4, L1, V1, Durchmesser größer 3 cm, sm3) oder T2N0-Tumoren, die eine Exstirpation ablehnen, ist die Radio(chemo-) therapie, gefolgt von lokaler Exzision/transanaler endoskopischer Mikrochirurgie oder einer wait-and-see Strategie bei klinisch kompletter Remission eine Behandlungsoption @DeutscheKrebsgesellschaftEtAl2019 

Laut NCCN Leitlinie @NationalComprehensiveCancerNetwork2025a können bei hochrisiko cT1–2, N0 Tumore eine Radiochemotherapie mit Capecitabin oder 5-Fluorouracil (5-FU), oder eine Kurzzeit-RT gefolgt von FOLFOX or CAPEOX erfolgen. 

Zu den Hochrisikomerkmalen gehören positive Ränder, lymphatische Invasion, schlecht differenzierte Tumore oder sm3-Invasion (submuköse Invasion bis zum unteren Drittel der Submukosa).



#### Tumoren des unteren und mittleren Rektumdrittels

##### Stadium II/III (cT3/4 und/oder cN+)

Eine neoadjuvante Radiochemotherapie oder KurzzeitRadiotherapie soll erfolgen. @DeutscheKrebsgesellschaftEtAl2019 

**Ausnahmen @DeutscheKrebsgesellschaftEtAl2019 :**

- cT1/2-Tumore im unteren und mittleren Drittel mit bildgebend fraglichen Lymphknotenbefall.
- cT3a/b-Tumore im mittleren Drittel mit in der MRT nur limitierter Infiltration ins perirektale Fettgewebe (cT3a: <1 mm, cT3b: 1-5 mm) und ohne bildgebenden Verdacht auf Lymphknotenmetastasen oder extra-muraler Gefäßinvasion (EMVI-) bei adäquater Qualitätssicherung der MRT-Diagnostik und der TME-Chirurgie.

##### Weitere Stadien 

Laut Therapie-Algorithmus für die Stadien I-III der Onkopedia Leitlinie: @Ralf-DieterHofheinzEtAl2025

##### cT1-2 N0

- kurzzeitige Strahlentherapie (5 x 5 Gy) oder 

- kombinierte Radiohemotherapie mit Einzeldosen von 1,8-2,0 Gy bis zu einer Gesamtdosis von 45-50,4 Gy.

Beide Konzepte + Watch and wait

##### cT2 N+, cT3

- kombinierte Radiohemotherapie ± Brachytherapie oder
- Totales neoadjuvantes Konzept 

Beide Konzepte + Watch and wait

##### cT4, mrCRM+, EMVI+, N2, laterale LK+

- Totales neoadjuvantes Konzept 

##### Rektumerhalt ***nicht*** intendiert oder nicht sinnvoll

###### Vorliegen von High-Risk-Kriterien

TNT bevorzugt (ab T3)

###### Keine High-Risk-Kriterien

####### cT1N0

- Lokale Therapie
- TME

####### cT2 N0/N+
- TME 

####### cT3 N0/N+ mittleres Drittel

- TME oder
- Perioperative Chemotherapie oder
- RT/RCT -> TME

####### cT3 N0/N+ unteres Dritte

- RT/RCT -> TME oder
- Perioperative Chemotherapie

##### Tumore im oberen Rektumdrittel

Rektumkarzinome im oberen Drittel ohne Risikokonstellation für ein Lokal-rezidiv sollen primär operiert. Jedoch eine präoperative Radio-/ Radiochemotherapie ***kann***, Bei einer Risikokonstellation, 
erfolgen @DeutscheKrebsgesellschaftEtAl2019 z.B.:

- T4 
- mrCRM+
- bildgebend eindeutiger und ausgedehnter Lymphknotenbefall 


#### Kurzzeitige vs. langzeitige RT

Die neoadjuvante Radiotherapie kann entweder als Kurzzeitbestrahlung mit 5 x 5 Gy gefolgt von sofortiger Operation oder als konventionell fraktionierte Radiochemotherapie (1.8-2.0 Gy bis 45-50.4 Gy) mit einem Intervall von 6-8 Wochen bis zur Operation erfolgen. @DeutscheKrebsgesellschaftEtAl2019


#### Kurzzeitige RT (5×5 Gy)

Für Patienten bei denen ein Downsizing angestrebt ist, kann auch die Kurzzeitbestrahlung mit längerem Intervall bis zu 12 Wochen zur Operation (mit und ohne neoadjuvante Chemotherapie) durchgeführt werden.

#### konventionelle CRT (45-50,4 Gy)

Eine konventionelle präoperative Radiochemotherapie **soll** in folgenden Fällen durchgeführt werden @DeutscheKrebsgesellschaftEtAl2019 :

- T4-Tumoren
- Nähe des Tumors zur mesorektalen Fazie (<1-2 mm)
- tiefliegenden Tumoren mit intendiertem Sphinktererhalt 

#### Boost-Protokolle für lokal fortgeschrittene Erkrankungen





## Gerätearzt

Behandlung von radiogener Toxizitäten

Kriterien für die Unterbrechung/Modifikation der Behandlung

## Gleichzeitige systemische Therapie
Spezifikationen des Chemotherapieschemas
Capecitabin-Dosierung
Protokolle für die kontinuierliche 5-FU-Infusion
Anforderungen an die Laborüberwachung
Kriterien für Dosisänderungen bei Toxizitäten

## Bewertung des Ansprechens auf die Behandlung

Durch die neoadjuvante Radiochemotherapie und entsprechende Remission kann u. U. trotz primär nicht für möglich gehaltenen Sphinktererhaltes eine Schließmuskel erhaltende Rektumresektion möglich werden. 
Deshalb sollte diesbezüglich frühestens 6 Wochen nach Abschluss der Radiochemotherapie eine Reevaluation stattfinden. @DeutscheKrebsgesellschaftEtAl2019

Zeitplan für die Bildgebung nach der Behandlung
MRT-Interpretationskriterien für das Ansprechen
Vollständiges Protokoll zur Bewertung des klinischen Ansprechens

### Kriterien für die Zulässigkeit des Watch-and-Wait-Protokolls

Voraussetzung ist die gründliche Aufklärung über die noch unzureichende Validierung dieses Vorgehens und die Bereitschaft des Patienten, sich einer sehr engmaschigen mindestens 5-jährigen Nachsorge zu unterziehen. @DeutscheKrebsgesellschaftEtAl2019

## Nachsorge
Häufigkeit der Überwachungsbilder
Anforderungen an Laboruntersuchungen
Zeitplan für die körperliche Untersuchung
Leitlinien für die Überwachung der Spättoxizität


## Anforderungen an die Dokumentation
Elemente für wöchentliche Kontrollbesuche während der Behandlung
Komponenten der Zusammenfassung am Ende der Behandlung
Standards für die Dokumentation der Nachbeobachtung
Einstufung der Toxizität und Berichterstattung (CTCAE v5.0)

## Wichtige Studien 
CAO/ARO/AIO-94
